# Generated by Django 4.1.7 on 2024-07-23 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dgm_app', '0002_documents_immigrés_sejours'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Immigrés',
            new_name='Immigres',
        ),
        migrations.CreateModel(
            name='Demandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avis', models.BooleanField(default=False)),
                ('date_demande', models.DateTimeField(auto_now=True)),
                ('lu', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgm_app.documents')),
                ('immigre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgm_app.immigres')),
                ('sejour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgm_app.sejours')),
            ],
            options={
                'db_table': 'Demandes',
            },
        ),
    ]
