# Generated by Django 4.1.7 on 2024-07-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgm_app', '0003_rename_immigrés_immigres_demandes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandes',
            name='avis',
            field=models.BooleanField(),
        ),
    ]
