# Generated by Django 4.1.7 on 2024-07-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgm_app', '0005_alter_demandes_avis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandes',
            name='avis',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
